server:
  port: 7001
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/szwkang/cloudconfig #é…ç½®æ–‡ä»¶æ‰?åœ¨ä»“åº?
#          search-paths: /config
#          default-label: master
        git:
          uri: https://github.com/szwkang/cloudconfig.git
          force-pull: true
  rabbitmq:
    host: 192.168.186.149
    password: admin
    username: admin
    port: 5672
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
management: # æš´éœ²è§¦å‘æ¶ˆæ¯æ€»çº¿çš„åœ°å?
  endpoints:
    web:
      exposure:
        include: "bus-refresh"